# Generated by Django 4.2.7 on 2023-11-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedcategories',
            options={'verbose_name_plural': 'liked categories'},
        ),
    ]
