# Generated by Django 4.2.7 on 2023-11-16 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_alter_book_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_likedcategories_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('about_me', models.TextField(max_length=10000)),
                ('liked_categories', models.ManyToManyField(to='library.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'liked categories',
            },
        ),
        migrations.DeleteModel(
            name='LikedCategories',
        ),
    ]
