# Generated by Django 4.2.7 on 2023-11-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_delete_likedcategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
