# Generated by Django 4.2.7 on 2023-11-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default.jpeg', null=True, upload_to='images/'),
        ),
    ]
