# Generated by Django 4.2.7 on 2023-11-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_rename_option_shelfoption_shelf_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfoption',
            options={'verbose_name_plural': 'Shelf Option'},
        ),
    ]
