# Generated by Django 4.2.7 on 2023-11-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_alter_shelfoption_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfitem',
            name='shelf_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.shelfoption'),
        ),
    ]
