# Generated by Django 4.2.7 on 2023-11-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_alter_shelfitem_shelf_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelfitem',
            old_name='shelf_option',
            new_name='shelf',
        ),
    ]
