# Generated by Django 4.2.7 on 2023-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0007_rename_shelf_option_shelfitem_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfoption',
            name='slug',
            field=models.SlugField(default='None', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelfoption',
            name='shelf_option',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
