# Generated by Django 4.2.7 on 2023-11-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0008_shelfoption_slug_alter_shelfoption_shelf_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfitem',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_item', to='shelf.shelfoption'),
        ),
    ]
