# Generated by Django 4.2.7 on 2023-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_rate_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
